import type { Metadata } from 'next';

import '@/app/globals.css';

import localFont from 'next/font/local';

import { GlobalAlert, GlobalLoading, RouterWrapper } from '@/components/common';
// import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

import RootPageTransition from '@/components/layout/RootPageTransition';
import { Toaster } from '@/components/ui/sonner';
import ReactQueryProvider from '@/providers/ReactQueryProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = Readonly<{
  children: React.ReactNode;
}>;

const pretendard = localFont({
  src: '../static/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <RouterWrapper>
      <html lang="en" className={pretendard.variable}>
        <body className="min-h-dvh flex flex-col">
          <ReactQueryProvider>
            <RootPageTransition>{children}</RootPageTransition>
            {/* <ReactQueryDevtools initialIsOpen={false} /> */}
            <GlobalAlert />
            <Toaster />
            <GlobalLoading />
          </ReactQueryProvider>
        </body>
      </html>
    </RouterWrapper>
  );
}
