export const productMockData = [
  {
    productId: '1',
    productName: '관아수제차 세작(녹차) 유기농 하동녹차(80g)',
    categoryId: 'greenTea',
    categoryName: '녹차',
    images: [
      '/images/product/greenTea/thumbnail/greenTeaSejak_1.webp',
      '/images/product/greenTea/thumbnail/greenTeaSejak_2.webp',
    ],
    infos: [
      '/images/product/greenTea/info/greenTeaSejak_1.webp',
      '/images/product/greenTea/info/greenTeaSejak_2.webp',
      '/images/product/greenTea/info/greenTeaSejak_3.webp',
      '/images/product/greenTea/info/greenTeaSejak_4.webp',
      '/images/product/greenTea/info/greenTeaSejak_5.webp',
      '/images/product/greenTea/info/greenTeaSejak_6.webp',
      '/images/product/greenTea/info/greenTeaSejak_7.webp',
      '/images/product/greenTea/info/greenTeaSejak_8.webp',
      '/images/product/greenTea/info/greenTeaSejak_9.webp',
      '/images/product/greenTea/info/greenTeaSejak_10.webp',
      '/images/product/greenTea/info/greenTeaSejak_11.webp',
      '/images/product/greenTea/info/greenTeaSejak_12.webp',
    ],
    price: 70000,
    shippingPrice: 0,
    createdAt: '2025-12-05T14:26:16',
    createdBy: null,
    modifiedAt: '2025-12-05T14:26:16',
    modifiedBy: null,
  },
  {
    productId: '2',
    productName: '관아수제차 우전 유기농 하동녹차(80g)',
    categoryId: 'greenTea',
    categoryName: '녹차',
    images: [
      '/images/product/greenTea/thumbnail/greenTeaUjeon_1.webp',
      '/images/product/greenTea/thumbnail/greenTeaUjeon_2.webp',
      '/images/product/greenTea/thumbnail/greenTeaUjeon_3.webp',
    ],
    infos: [
      '/images/product/greenTea/info/greenTeaUjeon_1.webp',
      '/images/product/greenTea/info/greenTeaUjeon_2.webp',
      '/images/product/greenTea/info/greenTeaUjeon_3.webp',
      '/images/product/greenTea/info/greenTeaUjeon_4.webp',
      '/images/product/greenTea/info/greenTeaUjeon_5.webp',
      '/images/product/greenTea/info/greenTeaUjeon_6.webp',
      '/images/product/greenTea/info/greenTeaUjeon_7.webp',
      '/images/product/greenTea/info/greenTeaUjeon_8.webp',
      '/images/product/greenTea/info/greenTeaUjeon_9.webp',
      '/images/product/greenTea/info/greenTeaUjeon_10.webp',
      '/images/product/greenTea/info/greenTeaUjeon_11.webp',
      '/images/product/greenTea/info/greenTeaUjeon_12.webp',
    ],
    price: 110000,
    shippingPrice: 0,
    createdAt: '2025-12-05T14:26:16',
    createdBy: null,
    modifiedAt: '2025-12-05T14:26:16',
    modifiedBy: null,
  },
  {
    productId: '3',
    productName: '관아수제차 녹차 드립백',
    categoryId: 'greenTea',
    categoryName: '녹차',
    images: [
      '/images/product/greenTea/thumbnail/greenTeaDripBag_1.webp',
      '/images/product/greenTea/thumbnail/greenTeaDripBag_2.webp',
    ],
    infos: [
      '/images/product/greenTea/info/greenTeaDripBag_1.webp',
      '/images/product/greenTea/info/greenTeaDripBag_2.webp',
      '/images/product/greenTea/info/greenTeaDripBag_3.webp',
      '/images/product/greenTea/info/greenTeaDripBag_4.webp',
      '/images/product/greenTea/info/greenTeaDripBag_5.webp',
      '/images/product/greenTea/info/greenTeaDripBag_6.webp',
    ],
    price: 10000,
    shippingPrice: 4000,
    createdAt: '2025-12-05T14:26:16',
    createdBy: null,
    modifiedAt: '2025-12-05T14:26:16',
    modifiedBy: null,
  },
  {
    productId: '4',
    productName: '관아수제차 발효차(홍차) 유기농 하동홍차(80g)',
    categoryId: 'blackTea',
    categoryName: '발효차',
    images: [
      '/images/product/blackTea/thumbnail/fermentedTea_1.webp',
      '/images/product/blackTea/thumbnail/fermentedTea_2.webp',
    ],
    infos: [
      '/images/product/blackTea/info/fermentedTea_1.webp',
      '/images/product/blackTea/info/fermentedTea_2.webp',
      '/images/product/blackTea/info/fermentedTea_3.webp',
      '/images/product/blackTea/info/fermentedTea_4.webp',
      '/images/product/blackTea/info/fermentedTea_5.webp',
      '/images/product/blackTea/info/fermentedTea_6.webp',
      '/images/product/blackTea/info/fermentedTea_7.webp',
    ],
    price: 60000,
    shippingPrice: 0,
    createdAt: '2025-12-05T14:26:16',
    createdBy: null,
    modifiedAt: '2025-12-05T14:26:16',
    modifiedBy: null,
  },
  {
    productId: '5',
    productName: '관아수제차 홍차 드립백',
    categoryId: 'blackTea',
    categoryName: '발효차',
    images: ['/images/product/blackTea/thumbnail/fermentedTeaDripBag_1.webp'],
    infos: [
      '/images/product/blackTea/info/fermentedTeaDripBag_1.webp',
      '/images/product/blackTea/info/fermentedTeaDripBag_2.webp',
      '/images/product/blackTea/info/fermentedTeaDripBag_3.webp',
      '/images/product/blackTea/info/fermentedTeaDripBag_4.webp',
      '/images/product/blackTea/info/fermentedTeaDripBag_5.webp',
      '/images/product/blackTea/info/fermentedTeaDripBag_6.webp',
    ],
    price: 10000,
    shippingPrice: 4000,
    createdAt: '2025-12-05T14:26:16',
    createdBy: null,
    modifiedAt: '2025-12-05T14:26:16',
    modifiedBy: null,
  },
  {
    productId: '6',
    productName: '하동 가을무우차 무카페인 자연차 전통차 관아수제차',
    categoryId: 'substituteTea',
    categoryName: '대용차',
    images: [
      '/images/product/substituteTea/thumbnail/autumnRadishTea_1.webp',
      '/images/product/substituteTea/thumbnail/autumnRadishTea_2.webp',
    ],
    infos: [
      '/images/product/substituteTea/info/autumnRadishTea_1.webp',
      '/images/product/substituteTea/info/autumnRadishTea_2.webp',
      '/images/product/substituteTea/info/autumnRadishTea_3.webp',
      '/images/product/substituteTea/info/autumnRadishTea_4.webp',
      '/images/product/substituteTea/info/autumnRadishTea_5.webp',
      '/images/product/substituteTea/info/autumnRadishTea_6.webp',
      '/images/product/substituteTea/info/autumnRadishTea_7.webp',
      '/images/product/substituteTea/info/autumnRadishTea_8.webp',
      '/images/product/substituteTea/info/autumnRadishTea_9.webp',
    ],
    price: 25000,
    shippingPrice: 4000,
    createdAt: '2025-12-05T14:26:16',
    createdBy: null,
    modifiedAt: '2025-12-05T14:26:16',
    modifiedBy: null,
  },
  {
    productId: '7',
    productName: '하동 야생 쑥차 관아수제차 무카페인 건강차',
    categoryId: 'substituteTea',
    categoryName: '대용차',
    images: ['/images/product/substituteTea/thumbnail/wildMugwortTea_1.webp'],
    infos: [
      '/images/product/substituteTea/info/wildMugwortTea_1.webp',
      '/images/product/substituteTea/info/wildMugwortTea_2.webp',
      '/images/product/substituteTea/info/wildMugwortTea_3.webp',
      '/images/product/substituteTea/info/wildMugwortTea_4.webp',
      '/images/product/substituteTea/info/wildMugwortTea_5.webp',
      '/images/product/substituteTea/info/wildMugwortTea_6.webp',
      '/images/product/substituteTea/info/wildMugwortTea_7.webp',
      '/images/product/substituteTea/info/wildMugwortTea_8.webp',
      '/images/product/substituteTea/info/wildMugwortTea_9.webp',
    ],
    price: 30000,
    shippingPrice: 4000,
    createdAt: '2025-12-05T14:26:16',
    createdBy: null,
    modifiedAt: '2025-12-05T14:26:16',
    modifiedBy: null,
  },
  {
    productId: '8',
    productName: '구기자차 무카페인 유기농 전통차 관아수제차',
    categoryId: 'substituteTea',
    categoryName: '대용차',
    images: ['/images/product/substituteTea/thumbnail/gugijaTea_1.webp'],
    infos: [
      '/images/product/substituteTea/info/gugijaTea_1.webp',
      '/images/product/substituteTea/info/gugijaTea_2.webp',
      '/images/product/substituteTea/info/gugijaTea_3.webp',
      '/images/product/substituteTea/info/gugijaTea_4.webp',
      '/images/product/substituteTea/info/gugijaTea_5.webp',
      '/images/product/substituteTea/info/gugijaTea_6.webp',
      '/images/product/substituteTea/info/gugijaTea_7.webp',
      '/images/product/substituteTea/info/gugijaTea_8.webp',
      '/images/product/substituteTea/info/gugijaTea_9.webp',
    ],
    price: 70000,
    shippingPrice: 0,
    createdAt: '2025-12-05T14:26:16',
    createdBy: null,
    modifiedAt: '2025-12-05T14:26:16',
    modifiedBy: null,
  },
  {
    productId: '9',
    productName: '하동 목련꽃차 무카페인 꽃차 관아수제차 지리산 전통차',
    categoryId: 'substituteTea',
    categoryName: '대용차',
    images: [
      '/images/product/substituteTea/thumbnail/magnoliaFlowerTea_1.webp',
      '/images/product/substituteTea/thumbnail/magnoliaFlowerTea_2.webp',
    ],
    infos: [
      '/images/product/substituteTea/info/magnoliaFlowerTea_1.webp',
      '/images/product/substituteTea/info/magnoliaFlowerTea_2.webp',
      '/images/product/substituteTea/info/magnoliaFlowerTea_3.webp',
      '/images/product/substituteTea/info/magnoliaFlowerTea_4.webp',
      '/images/product/substituteTea/info/magnoliaFlowerTea_5.webp',
      '/images/product/substituteTea/info/magnoliaFlowerTea_6.webp',
      '/images/product/substituteTea/info/magnoliaFlowerTea_7.webp',
      '/images/product/substituteTea/info/magnoliaFlowerTea_8.webp',
      '/images/product/substituteTea/info/magnoliaFlowerTea_9.webp',
    ],
    price: 30000,
    shippingPrice: 4000,
    createdAt: '2025-12-05T14:26:16',
    createdBy: null,
    modifiedAt: '2025-12-05T14:26:16',
    modifiedBy: null,
  },
];
